### PR TITLE
feat: no-discriminator-property-in-object rule

### PR DESCRIPTION
**Pull request by andriyl**

### CODE REVIEW

**Comment by adamaltman** [comment]
This one definitely needs tests.

**Review by almoshaks69 — APPROVED** [review]

**Review by almoshaks69 — APPROVED** [review]

**Comment by adamaltman** [comment]
Anybody want to resolve conflicts and add tests?

**Comment by tatomyr** [comment]
Sure @adamaltman, will check this during the cooldown. Any context on this?

**Comment by AntonKozachuk** [comment]
I discussed this PR with @RomanHotsiy and it looks like we should close it for several reasons:
1) this code doesn't serve the chosen purpose;
2) we probably won't be able to resolve this within the rule and will need to add this to the `core` package;
3) it seems to be a complicated task and needs additional investigation.

**Comment by RomanHotsiy** [comment]
Well, we should not just close this PR. We should open a corresponding issue (if it doesn't exists).

**Comment by AntonKozachuk** [comment]
@RomanHotsiy it already exists - https://github.com/Redocly/redocly-cli/issues/210

**Pull request closed without merging**
