### PR TITLE
Fix : Filter-out does not filter out when value is set to false (bool) #753

### PR DESCRIPTION
**Pull request by deBarrosS**
### What ?

- Fix use of if guards on filtering in and out some nodes from an openapi file. 

### Why ?

- The use of **! operator*** for checking whether a value was undefined also checked out false (boolean) and null values. What made it impossible to use those values for filtering nodes out of the file.
- As a border effect, this problem didn't occur while filtering **in** properties that had these values (false/null) but not for the "proper reason".

### How ?

- Explicitly use **"=== undefined"**  to verify if the structure hasn't been given as a parameter to the function call instead of using the **! operator** 
- This allows the use of both false and null values to filter nodes in or out an openapi file 

## Reference

[Filter-out does not filter out when value is set to false (bool) #753](https://github.com/Redocly/redocly-cli/issues/753)

## Testing

- Test if the nodes containing the given properties with false or null values are properly removed from the input file.

## Check yourself

- [ ✅  ] Code is linted
- [ ❌  ] Tested with redoc/reference-docs/workflows
- [ ✅  ] All new/updated code is covered with tests

## Security

- [ ✅ ] Security impact of change has been considered
- [ ❔  ] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by deBarrosS** [comment]
@RomanHotsiy a bit later than I thought but there it is 😬

**Review by RomanHotsiy — APPROVED** [review]

**Comment by RomanHotsiy** [comment]
Amazing, you even added tests 👏 !

@tatomyr plz merge it and release after you review it.

**Comment by tatomyr** [comment]
LGTM.

@deBarrosS thanks for your contribution. I'm going to merge and release the new version early next week.

**Review by tatomyr — APPROVED** [review]

**Comment by deBarrosS** [comment]
My pleasure, @tatomyr . Thank you for the reply (and obviously for this great tool) :+1: :smile:

**Pull request merged**
