### PR TITLE
chore: fix OasSchema types

### PR DESCRIPTION
**Pull request by vladkens**
## What/Why/How?

Fix wrong typing for `Oas3_1Schema`.

When using `type` in TypeScript instead of `interface`, need to omit all overridden fields first.

```
type A = { type: string }
type B = A & { type: string | string[] }
const b: B = { type: ["string", "number"] } // typescript say error here

// so it should be
type C = Omit<A, "type"> & { type: string | string[] }
const c: C = { type: ["string", "number"] } // no problem now
```

## Reference

https://www.typescriptlang.org/play?ssl=7&ssc=62&pln=1&pc=1#code/C4TwDgpgBAglC8UDeVSQFxQM7AE4EsA7AcygF8AoNaAIQVigDJlVwJMcCSoAfbPIsQDaAXXIUAxgHtCOKACNMdRCmqYhAIk6CNAGigbCAVwC28iLg1iyUAPS3WkLBIJhg2AIYgoF3FNxQABYWEBQU9thSUPjuWIFSRgA2ACYKodRQAML0APImMQA8MPoa1BoAfEwsavxcpHzaJKLi0rLuEpjZKo7sUJqNxHoGxmYWVuR2DoRRYH7yiRAmUNMA7kA

## Check yourself

- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows (internal)
- [ ] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by tatomyr** [comment]
Thanks for pointing this out, @vladkens!

I'd suggest using `interface` instead. I'm unsure of the initial reason for using the `type`. Moreover, there are more properties to cover here: `properties`, `additionalProperties`, `items`, `allOf` &c. - all of them should also be `Oas3_1Schema` instead of `Oas3Schema`. Don't you mind tackling that as well?

**Comment by lornajane** [comment]
@tatomyr I see that you asked for further changes on this pull request. Can the existing changes be reviewed as they are, or do your requested updates also need to be included to make it useful?

**Comment by vladkens** [comment]
Hi, @tatomyr. Didn't see the notification in time.

Fixed nested typing too and made Oas3_1Schema as interface. Also put the general properties for v3 & v3.1 in a separate internal interface.

Please re-view PR.

From my side checked with:
```sh
npm run lint
npm run typecheck
npm run prettier:check
```

**Comment by tatomyr** [comment]
Thank you @vladkens very much for handling all the comments! I'll review and merge your PR soon.

**Review by tatomyr — APPROVED** [review]
Looks good to me. Thank you again for your efforts @vladkens! 
The changes will be available in the next release.

**Pull request merged**
