### PR TITLE
Lets talk about API Style Guides

### PR DESCRIPTION
**Pull request by philsturgeon**
## What/Why/How?

Updating README to talk about API Style Guides, to be consistent with how other tools talk about it. 

If this approach is good we can update the rest of the docs to follow along the same lines, downplaying "API Standards" (the word standard is already massively overloaded in the world of APIs) and hype up Rulesets are a technical implementation of an API Style Guide (Rulesets focused on helping you design and build better APIs) or OpenAPI Style Guides (Rulesets helping you write better OpenAPI, but doesn't really tell you how to write the API itself.)

### CODE REVIEW

**Comment by philsturgeon** [comment]
@lornajane 🙌🏻

**Comment by lornajane** [comment]
I need to think more about this. I don't use the style guide language because it sounds a bit vague and optional, like "try to avoid passive voice in prose". It's more like coding standards or strict typing in how fundamental adopting this approach is. I'm not terribly worried about what other people call things, but I can see that "standard" is doing a lot of work!

**Comment by lornajane** [comment]
Could we settle on something like:

API governance: the practice, process and tools of making APIs more excellent on purpose

Guidelines: the written word version of the standard expected from this API. These are the lines that will guide us to success.

Ruleset: programmatic checks that we run against an API.

Governance is the umbrella term, and includes both the guidelines and the rulesets... could this work and be understood?

**Comment by philsturgeon** [comment]
Sure, its nice and consistent.

**Review by lornajane — APPROVED** [review]
Thanks @philsturgeon !

**Pull request merged**
