### PR TITLE
chore: deploy docker container to GitHub registry

### PR DESCRIPTION
**Pull request by IgorKarpiuk**
## What/Why/How?

Deploy docker container to GitHub registry

## Reference
Closes: https://github.com/Redocly/redocly-cli/issues/875
## Check yourself

- [ ] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [ ] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Review by AlexVarchuk — APPROVED** [review]

**Comment by lornajane** [comment]
Do we need to have any metadata, descriptions, tags, or documentation such as installation/usage instructions for the registry?

**Comment by IgorKarpiuk** [comment]
@lornajane I think we just need to update the docs [here](https://redocly.com/docs/cli/installation/#a-iddockerarun-commands-inside-docker)

**Comment by lornajane** [comment]
Are you updating those, or do you want to give me some clues on how I should do that? Let's capture it as a followup (non-GA) issue

**Comment by tatomyr** [comment]
@lornajane we are going to prepare a small draft.

**Pull request merged**
