### PR TITLE
fix: show 'referenced from' in the lint error message

### LINKED ISSUE #767: Wrong lint message when referencing from a wrong location
**Describe the bug**

If a valid part of a definition is being referenced from a section that does not expect this syntax, the linter shows an incorrect message inside the valid part.

**To Reproduce**

Consider this definition: 

```
# openapi.yaml

openapi: 3.0.0
components:
  requestBodies:
    CreateContainer:
      content:
        application/json:
          schema:
            type: object
  schemas:
    PipeContainerCreate:
      title: PipelineContainerCreate
      allOf:
      - "$ref": "#/components/requestBodies/CreateContainer"
   ```

Run `redocly lint openapi.yaml  --extends minimal`

Although the `requestBody` could receive the `content` field, linter notes that `Property `content` is not expected here.`.

**Expected behavior**

We need to handle this common issue and show a proper message and a "referenced from".

**Redocly Version(s)**
`1.0.0-beta.104`

**`Node.js` Version(s)**
`v16.14.0`

**Additional context**
See this [conversation](https://redoc-ly.slack.com/archives/C02UHE7EL3E/p1657730049335399) for additional context.

### PR DESCRIPTION
**Pull request by AntonKozachuk**
## What/Why/How?
Show the `referenced from` part for the spec rule error in case we are reporting on the `$ref`.

## Reference
Partially resolves #767.

## Testing
Tested locally.

## Screenshots (optional)
image

## Check yourself

- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [x] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Review by tatomyr — APPROVED** [review]

**Review by RomanHotsiy — APPROVED** [review]

**Comment by AntonKozachuk** [comment]
Updated the format, now looks like this: 
image

**Comment by tatomyr** [comment]
LGTM

**Review by RomanHotsiy — APPROVED** [review]

**Comment by adamaltman** [comment]
@AntonKozachuk this is a bad merge. Please merge and squash all commits. Now we have non-conventional commits in the commit history. @RomanHotsiy do you think it is worth fixing those with a rebase?

**Comment by RomanHotsiy** [comment]
I just rebased and force-pushed it. Also disabled a "merge" commit for this repo.

**Comment by AntonKozachuk** [comment]
@adamaltman @RomanHotsiy apologies for the inconvenience, I probably used rebase instead of squash here.

**Pull request merged**
