### PR TITLE
Enhance no-http-verbs-in-paths with Exclude Paths option

### PR DESCRIPTION
**Pull request by Ayush9026**
## What/Why/How?

**Solution:**
Implemented a new feature to allow listing excluded paths directly in the rule configuration. This enhancement provides a more streamlined approach to handling excluded paths, improving the overall usability and effectiveness of the rule.

**Changes Made:**

Added support for the "excludedPaths" option in the "no-http-verbs-in-paths" rule configuration.
Updated documentation and examples to reflect the new functionality.

**Benefits:**

Reduces false positives by excluding specific paths from rule evaluation.
Improves developer experience by providing a built-in mechanism for managing excluded paths.
Aligns with best practices for rule configuration and customization.

## Reference
https://github.com/Redocly/redocly-cli/issues/1501

## Check yourself

- [ ] Code changed? - Tested with redoc/reference-docs/workflows (internal)
- [ ] All new/updated code is covered with tests
- [ ] New package installed? - Tested in different environments (browser/node)

## Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by tatomyr** [comment]
Hi @Ayush9026, did you forget to push the actual changes?

**Comment by Ayush9026** [comment]
@tatomyr sir i pushed actual changes but i will check it again. Thanks for pointing that out!

**Comment by tatomyr** [comment]
@Ayush9026 do you mean that this PR only contains the docs changes?

**Comment by Ayush9026** [comment]
Yes @tatomyr sir this PR only contain doc changes but i think i have to make changes in codebase too.

**Comment by tatomyr** [comment]
@Ayush9026 yes, you have to make the corresponding code changes in order to get this PR approved. Please notice that every issue that isn't marked with `documentation` or `Type: Docs` labels is supposed to contain some code changes 🙂. If you would like to contribute to the documentation instead, please choose tickets with the corresponding labels. 

Please let me know if I should wait for the code changes or if I can close the issue.

**Comment by Ayush9026** [comment]
@tatomyr sir , got it! I'll proceed with the necessary code changes to address the issue. Thanks for the clarification and guidance!

**Comment by lornajane** [comment]
Since we don't have the change in place yet, I'll close this pull request. Please do feel free to re-open it when you have something for us to review.

**Pull request closed without merging**
