### PR TITLE
fix: rename spec-ref-validation to spec-strict-refs

### PR DESCRIPTION
**Pull request by IgorKarpiuk**
## What/Why/How?

Rename `spec-ref-validation` to `spec-strict-refs`

## Check yourself

- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [x] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by RomanHotsiy** [comment]
The PR title and description is invalid. In code it `spec-strict-refs` but in descriptions its `spec-restrict-refs`.

**Review by tatomyr — APPROVED** [review]

**Comment by IgorKarpiuk** [comment]
> The PR title and description is invalid. In code it `spec-strict-refs` but in descriptions its `spec-restrict-refs`.

Fixed, Thank you

**Review by RomanHotsiy — APPROVED** [review]
LGTM

Let's see what @adamaltman and @lornajane think about this change.

Maybe they have even better idea.

More details here: https://github.com/Redocly/redocly-cli/pull/1112#discussion_r1214058103

**Comment by lornajane** [comment]
It works for me. Thanks!

**Review by lornajane — APPROVED** [review]
Naming things is hard, but this is better :)

**Pull request merged**
