### PR TITLE
fix: push destination parsing

### PR DESCRIPTION
**Pull request by AntonKozachuk**
## Reference
https://github.com/Redocly/workflows/issues/2498

## Check yourself

- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [x] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Review by IgorKarpiuk — APPROVED** [review]

**Comment by RomanHotsiy** [comment]
@AntonKozachuk please add a description to PRs. Thanks.

**Comment by HyeonJi-Kang** [comment]
Hello,

I am running a command npx @redocly/cli push on Redocly CLI in circleCI pipeline and it worked really well last night. But suddenly it's giving this error.

#!/bin/bash -eo pipefail
npx @redocly/cli push
Destination argument value is not valid, please use the right format: <@organization-id/api-name@api-version>


Exited with code exit status 1
CircleCI received exit code 1
I think it is related to this merge: fix: push destination parsing (https://github.com/Redocly/redocly-cli/pull/890).

At first, I thought maybe circle CI image is missing redocly.yaml (config file), but those two commands are working fine.
npx @redocly/cli lint
npx @redocly/cli stats

Is it not allowed anymore to redocly push in CI docker image without a destination even though there is redocly.yaml (config file) exists in the root?

**Comment by mto-gambit** [comment]
Hi there, 

Find same issue than @HyeonJi-Kang since the version 1.0.0-beta.121. 

Not sure if the cause is the following but it seems the "organizationId" part of the regex is not recognised if organization contains an hyphen. 

image
vs 
image

**Comment by RomanHotsiy** [comment]
We're on it. Sorry for troubles.

**Comment by AntonKozachuk** [comment]
Hi @HyeonJi-Kang and @mto-gambit,

**Comment by HyeonJi-Kang** [comment]
Hi @AntonKozachuk 

I am afraid to say it, but it's still giving me the same error.
I have tried both with and without the version suffix. 
```
#!/bin/bash -eo pipefail
npx @redocly/cli@1.0.0-beta.122 push -b test
npm WARN exec The following package was not found and will be installed: @redocly/cli@1.0.0-beta.122
Destination argument value is not valid, please use the right format: <@organization-id/api-name@api-version>


Exited with code exit status 1
CircleCI received exit code 1
```
The same command works fine on my local terminal, but it just doesn't work on circle CI pipeline.

**Comment by mto-gambit** [comment]
Hi @AntonKozachuk 

Just confirming that the version `1.0.0-beta.122` fixed the issue for me, thanks !

However, I do not use CircleCI to push.

**Pull request merged**
