### PR TITLE
add contentSchema keyword

### PR DESCRIPTION
**Pull request by onavratil-monetplus**
## What/Why/How?

Added `contentSchema` keyword.

https://github.com/Redocly/redocly-cli/issues/1598#issuecomment-2183278049

## Check yourself

- [ ] Code changed? - Tested with redoc/reference-docs/workflows (internal)
- [ ] All new/updated code is covered with tests
- [ ] New package installed? - Tested in different environments (browser/node)

## Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by tatomyr** [comment]
Thanks for the contribution @onavratil-monetplus! Could you also add a patch level changeset as described in the [contributing guide](https://github.com/Redocly/redocly-cli/blob/main/CONTRIBUTING.md#pull-request-guidelines)?

**Comment by onavratil-monetplus** [comment]
Done, i included cli as well since the changes affect its behavior.

**Comment by tatomyr** [comment]
Oh, looks like you added the changeset file two times. Could you remove one? Otherwise all good, only waiting for @Redocly/technical-writers approval.

**Comment by onavratil-monetplus** [comment]
Sorry for the mix-up. Should be fixed now.

**Review by lornajane — APPROVED** [review]
Changelog is fine

**Review by tatomyr — APPROVED** [review]
Thank you @onavratil-monetplus for making Redocly CLI better!

**Comment by jeremyfiel** [comment]
fixes #1598

**Pull request merged**
