### PR TITLE
docs: Use a single sidebar for all Redocly CLI content

### PR DESCRIPTION
**Pull request by lornajane**
## What/Why/How?

The decorators had their own sub sidebar which meant those pages missed linking users to the rest of our content and could be disorientating. This pull request removes the extra sidebar, the decorators are already listed in the top-level sidebar for this project.

## Check yourself

- [x] Code is linted
- [x] Tested with redoc/reference-docs/workflows (internal)
- [x] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by tatomyr** [comment]
@lornajane could you attach a screenshot? I cannot figure out what has changed.

**Review by adamaltman — APPROVED** [review]

**Comment by adamaltman** [comment]
@tatomyr it changes the sidebar behavior. You can see a preview of the website in the checks there is a link.

image

**Comment by lornajane** [comment]
@tatomyr is right, the live site does the same thing as the preview at this point. But before we moved to the new platform, the decorators had a weird sidebar and I never understood why. I had deleted it on my local version, and now I can't see that it does anything any more so I removed it. As long as you think the current behaviour is okay, I think we're good.

**Review by tatomyr — APPROVED** [review]
Thanks for the explanation 👍

**Pull request merged**
