### PR TITLE
fix: update redocly.yaml validation

### PR DESCRIPTION
**Pull request by tatomyr**
## What/Why/How?

Redocly config validation update. 
Copied and pasted validation schemas from the Portal, and added additional 'rules' validation (`metadata-schema` and `custom-fields-schema`). 

## Testing

Tested on Portal playground's and Rebilly redocly.yaml files.

## Check yourself

- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows (internal)
- [ ] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by lornajane** [comment]
Are we asking docs in this pull request, or capturing in an issue what we need to add later? Link the issue if its separate

**Review by vital4u4ok — APPROVED** [review]

**Review by Oprysk — APPROVED** [review]

**Review by AlexVarchuk — APPROVED** [review]

**Comment by tatomyr** [comment]
@lornajane I don't think there's something to be documented here. We are only catching up with the Portal config, no changes to the CLI config itself.

**Review by SmoliyY — APPROVED** [review]
It also will be great to see some e2e test for validation of config. 
At least for cases with `metadata-schema` and `custom-fields-schema`

**Comment by lornajane** [comment]
Got it. I thought we were also adopting the rules and would need docs. Now I see it's just the validation

**Comment by tatomyr** [comment]
@SmoliyY I see your point, but those don't make sense in the CLI itself as they are not quite rules and are only related to the Portal.

**Pull request merged**
